export const PLACE_ORDER_STEP = 'PLACE_ORDER_STEP';
export const RESERVE_ITEMS_STEP = 'RESERVE_ITEMS_STEP';
export const CHARGE_PAYMENT_STEP = 'CHARGE_PAYMENT_STEP';
export const COMMIT_RESERVE_STEP = 'COMMIT_RESERVE_STEP';
